"""
seed_contexts.py — POSTs all seed data to the running bot in the correct order:
  1. Category contexts (5)
  2. Merchant contexts (10 from seed, expanded by generate_dataset.py if available)
  3. Customer contexts (15 from seed)
  4. Trigger contexts (25 from seed)

Usage:
  python seed_contexts.py [--url http://localhost:8000]
"""
import argparse, json, os, sys
import urllib.request
import urllib.error

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATASET_DIR = os.path.join(BASE_DIR, "dataset")
EXPANDED_DIR = os.path.join(BASE_DIR, "expanded")   # generated by generate_dataset.py


def post(url: str, payload: dict) -> dict:
    data = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(
        url,
        data=data,
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=10) as resp:
            return json.loads(resp.read())
    except urllib.error.HTTPError as e:
        body = e.read().decode()
        print(f"  HTTP {e.code}: {body[:200]}")
        return {}


def seed_categories(bot_url: str):
    print("\n-- Seeding categories --")
    cat_dir = os.path.join(DATASET_DIR, "categories")
    for fname in sorted(os.listdir(cat_dir)):
        if not fname.endswith(".json"):
            continue
        slug = fname.replace(".json", "")
        with open(os.path.join(cat_dir, fname), encoding="utf-8") as f:
            payload = json.load(f)
        body = {"scope": "category", "context_id": slug, "version": 1,
                "delivered_at": "2026-04-26T09:45:00Z", "payload": payload}
        resp = post(f"{bot_url}/v1/context", body)
        print(f"  {slug}: {resp.get('accepted', '?')} ack={resp.get('ack_id', '-')}")


def seed_merchants(bot_url: str):
    print("\n-- Seeding merchants --")
    # Try expanded first
    paths = []
    expanded_merchants = os.path.join(EXPANDED_DIR, "merchants.json")
    seed_merchants_file = os.path.join(DATASET_DIR, "merchants_seed.json")
    if os.path.exists(expanded_merchants):
        with open(expanded_merchants, encoding="utf-8") as f:
            merchants = json.load(f)
        if isinstance(merchants, list):
            paths = merchants
        elif isinstance(merchants, dict):
            paths = merchants.get("merchants", [])
    else:
        with open(seed_merchants_file, encoding="utf-8") as f:
            data = json.load(f)
        paths = data.get("merchants", [])

    for m in paths:
        mid = m.get("merchant_id", "unknown")
        body = {"scope": "merchant", "context_id": mid, "version": 1,
                "delivered_at": "2026-04-26T09:45:30Z", "payload": m}
        resp = post(f"{bot_url}/v1/context", body)
        status = resp.get("accepted", resp.get("reason", "?"))
        print(f"  {mid}: {status}")


def seed_customers(bot_url: str):
    print("\n-- Seeding customers --")
    # Try expanded first
    expanded_customers = os.path.join(EXPANDED_DIR, "customers.json")
    seed_customers_file = os.path.join(DATASET_DIR, "customers_seed.json")
    if os.path.exists(expanded_customers):
        with open(expanded_customers, encoding="utf-8") as f:
            customers = json.load(f)
        if isinstance(customers, list):
            items = customers
        else:
            items = customers.get("customers", [])
    else:
        with open(seed_customers_file, encoding="utf-8") as f:
            data = json.load(f)
        items = data.get("customers", [])

    for c in items:
        cid = c.get("customer_id", "unknown")
        body = {"scope": "customer", "context_id": cid, "version": 1,
                "delivered_at": "2026-04-26T09:46:00Z", "payload": c}
        resp = post(f"{bot_url}/v1/context", body)
        status = resp.get("accepted", resp.get("reason", "?"))
        print(f"  {cid}: {status}")


def seed_triggers(bot_url: str):
    print("\n-- Seeding triggers --")
    expanded_triggers = os.path.join(EXPANDED_DIR, "triggers.json")
    seed_triggers_file = os.path.join(DATASET_DIR, "triggers_seed.json")
    if os.path.exists(expanded_triggers):
        with open(expanded_triggers, encoding="utf-8") as f:
            data = json.load(f)
        items = data if isinstance(data, list) else data.get("triggers", [])
    else:
        with open(seed_triggers_file, encoding="utf-8") as f:
            data = json.load(f)
        items = data.get("triggers", [])

    for t in items:
        tid = t.get("id", "unknown")
        body = {"scope": "trigger", "context_id": tid, "version": 1,
                "delivered_at": "2026-04-26T10:00:00Z", "payload": t}
        resp = post(f"{bot_url}/v1/context", body)
        status = resp.get("accepted", resp.get("reason", "?"))
        print(f"  {tid}: {status}")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--url", default="http://localhost:8000")
    args = parser.parse_args()
    bot_url = args.url.rstrip("/")

    # Health check
    try:
        with urllib.request.urlopen(f"{bot_url}/v1/healthz", timeout=5) as r:
            health = json.loads(r.read())
            print(f"Bot healthy: {health}")
    except Exception as e:
        print(f"Bot not reachable at {bot_url}: {e}")
        sys.exit(1)

    seed_categories(bot_url)
    seed_merchants(bot_url)
    seed_customers(bot_url)
    seed_triggers(bot_url)
    print("\n-- Done. Verifying counts --")
    with urllib.request.urlopen(f"{bot_url}/v1/healthz", timeout=5) as r:
        h = json.loads(r.read())
        print(f"Contexts loaded: {h.get('contexts_loaded')}")


if __name__ == "__main__":
    main()
